services:

  nginx:
    container_name: nginx
    build: "requirements/nginx/"
    volumes:
      - static:${WWW_DIR}
    networks:
      - network
    ports:
      - "443:443"
    restart: always
    env_file:
      - .env
  # wordpress:
  #   env_file:
  #     - .env
  #   volumes:
  #       - static:${WWW_DIR}
  #   networks:
  #     - inception
  # mariadb:
  #   volumes:
  #     - db:${DB_DIR}
  #   networks:
  #     - inception

volumes:
  db:
    name: db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOLUME_PATH}/db
  static:
    name: static
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOLUME_PATH}/static

networks:
  network:
    driver: bridge