services:

  nginx:
    container_name: nginx
    build: "requirements/nginx/"
    volumes:
      - static:${WWW_DIR}
    networks:
      - network
    ports:
      - "443:443"
    restart: always
    env_file:
      - .env
    depends_on:
      - wordpress
  wordpress:
    container_name: wordpress
    build: "requirements/wordpress/"
    env_file:
      - .env
    volumes:
        - static:${WWW_DIR}
    networks:
      - network
    restart: always
    expose:
      - "9000"
    depends_on:
      mariadb:
        condition: service_healthy
  mariadb:
    container_name: maria-db
    build: "requirements/mariadb/"
    env_file:
      - .env
    volumes:
      - db:${DB_DIR}
    networks:
      - network
    restart: always
    healthcheck:
      test: ["CMD", "mariadb-check", "$MARIA_DB_NAME"]
      interval: 10s
      timeout: 10s
      retries: 10

volumes:
  db:
    name: db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOLUME_PATH}/db
  static:
    name: static
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOLUME_PATH}/static

networks:
  network:
    driver: bridge