services:

  nginx:
    container_name: nginx
    build: 
      context: "requirements/nginx/"
      args:
        - WWW_DIR
        - SSL_DIR
    volumes:
      - static:${WWW_DIR}
    networks:
      - network
    ports:
      - "443:443"
    restart: always
    env_file:
      - .env
    depends_on:
      - wordpress
  wordpress:
    container_name: wordpress
    build:
      context: "requirements/wordpress/"
      args:
        - WWW_DIR
        - SSL_DIR
    env_file:
      - .env
    volumes:
        - static:${WWW_DIR}
    networks:
      - network
    restart: always
    depends_on:
      - mariadb
  mariadb:
    container_name: maria-db
    build: "requirements/mariadb/"
    env_file:
      - .env
    volumes:
      - db:${DB_DIR}
    networks:
      - network
    restart: always

volumes:
  db:
    name: db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOLUME_PATH}/db
  static:
    name: static
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOLUME_PATH}/static

networks:
  network:
    driver: bridge